name: Enviar Email

on:
  schedule:
    - cron: '0 8 * * 3'  # Toda quarta-feira às 08:00 UTC (05:00 em Salvador)
  workflow_dispatch:  # Permite execução manual também (opcional)

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Run script
        run: python enviar_emails.py
        env:
          DIC_BASE: ${{ secrets.DIC_BASE }}     # Dicionário com senha, remetente e destinatários
          DIC_EMAIL: ${{ secrets.DIC_EMAIL }}   # Dicionário com assunto, corpo e anexos
